export type Section={id:string,title:string,paragraphs:string[],code?:string,language?:string};
export type Guide={slug:string,title:string,category:string,summary:string,goals:string[],sections:Section[],exercise:string[],answer:string,glossary:[string,string][],sources:{title:string,url:string}[]};
export const guides:Guide[]=[];
export function guideWords(g:Guide){return [g.title,g.summary,...g.goals,...g.sections.flatMap(s=>[s.title,...s.paragraphs]),...g.exercise,g.answer,...g.glossary.flat()].join(' ').split(/\s+/).length}
export function readingTime(g:Guide){return Math.ceil(guideWords(g)/180)}
guides.push({slug:'how-websites-work',title:'How websites work: from a click to a complete page',category:'Web foundations',summary:'Follow a browser request, understand the frontend and backend, and build a small page you can explain line by line.',goals:['Explain the browser–server relationship','Separate HTML, CSS, and JavaScript responsibilities','Build and troubleshoot a small interactive page'],sections:[
{id:'big-picture',title:'1. Start with the whole system',paragraphs:[`Imagine a school library website. A student wants to find a book, see whether a copy is available, and reserve it. On screen, this looks like a search field and a few buttons. Behind that interaction are separate responsibilities: showing the interface, receiving requests, applying borrowing rules, and keeping records. Learning web development becomes easier when you can name these responsibilities before choosing a framework.`,`The frontend is the part presented through the browser. The backend handles work on the server, such as deciding whether a reservation is allowed. A database keeps information that needs to survive beyond a single request. These are roles, not necessarily separate computers. A small project might place several roles together. A larger project might distribute them. Ask where each piece of work happens and which component owns each decision.`,`Draw three boxes: browser, application server, and database. Draw an arrow for a search request and another for its result. Label what travels on each arrow. This simple drawing can reveal missing assumptions more quickly than writing another component.`]},
{id:'journey',title:'2. Follow one request',paragraphs:[`When you enter a website address, the browser needs a way to reach the appropriate service. DNS helps resolve a hostname to addressing information. Network connections carry requests and responses; HTTPS adds protection through TLS. The browser requests a resource, and a server sends a response. Some responses contain HTML, while others contain an image, stylesheet, or data. Caches may satisfy some requests without contacting the original server.`,`Separate an address from a resource. In https://example.com/books, the hostname is example.com and the path is /books. The same host can provide many resources. A successful connection does not mean every path exists, and a working homepage does not prove that the search endpoint works. Each request has its own outcome.`,`Open your browser's developer tools and choose Network. Reload a page and observe the requests. Pick one document, one image, and one stylesheet. Compare their types and sizes. Do not worry about memorizing every column. Connect visible content to a real transfer instead of treating the entire page as one mysterious object.`]},
{id:'languages',title:'3. Give each language a clear job',paragraphs:[`HTML describes structure and meaning. A heading communicates hierarchy; a button communicates an action. CSS controls presentation, including spacing, color, layout, and adaptation to available space. JavaScript handles behavior such as reacting to a click or updating a result. The layers work together, but they should not obscure one another.`,`Consider a borrowing form. The label and input belong in HTML, the spacing belongs in CSS, and the response to submission belongs in JavaScript. If the page is unreadable until a script runs, ask whether essential content can be expressed in HTML first. If a clickable element is an action, start with a button so keyboard behavior comes with the correct element.`,`These boundaries help debugging. An item in the wrong position suggests a layout problem. A button that looks right but does nothing suggests an event or logic problem. Missing content suggests a rendering or data problem. This is a starting hypothesis, not a guarantee, but it gives your investigation direction.`]},
{id:'build',title:'4. Build a tiny interactive page',paragraphs:[`Save this example as index.html and open it in a browser. It has one job: update a message when a button is pressed. Keeping the exercise small makes it possible to understand every line. You do not need a database, package manager, or deployment service to learn this interaction.`,`The script appears after the elements it selects, so they exist when it runs. textContent updates plain text rather than interpreting the value as HTML. The status region helps announce the changed message to assistive technology. After clicking, use the Tab key to focus the button and activate it with the keyboard.`,`Modify the message, change the button label, and adjust the maximum width. Make one change at a time and predict its effect before reloading. Prediction turns copying into understanding. If the result differs, inspect the relevant element or read the console rather than randomly changing several lines.`],language:'HTML',code:`<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Library welcome</title>
  <style>
    body { font: 1rem/1.6 system-ui; max-width: 42rem; margin: 3rem auto; padding: 1rem; }
    button { font: inherit; padding: .7rem 1rem; }
  </style>
</head>
<body>
  <h1>Welcome to the library</h1>
  <p id="message" role="status">Ready to find your next book?</p>
  <button id="start" type="button">Start exploring</button>
  <script>
    const button = document.querySelector('#start');
    const message = document.querySelector('#message');
    button.addEventListener('click', () => {
      message.textContent = 'Choose a subject to learn today.';
    });
  </script>
</body>
</html>`},
{id:'state',title:'5. Understand what survives a reload',paragraphs:[`The message is temporary browser state. Refreshing restores its original value. A real reservation needs a durable record. The server should verify the user, check availability, and write a reservation to persistent storage. Showing a success message is not itself proof that a reservation was saved.`,`Imagine two students reserving the last copy at nearly the same time. A browser-only availability check can become outdated between viewing and submitting. The system that owns the record must enforce the rule when the change occurs. Interfaces can offer helpful early validation while the backend remains responsible for authoritative decisions.`,`For each feature, write down what the user sees, what the server must confirm, and what must be stored. Consider how the page behaves if the request fails. A useful error should preserve the student's input and explain a next action.`]},
{id:'debug',title:'6. Debug with evidence',paragraphs:[`Describe the failure precisely. “The page is broken” is difficult to investigate. “The button receives focus but the message never changes after activation” is more useful. Record expected behavior, actual behavior, and reproduction steps. Inspect the smallest relevant part of the system.`,`A misspelled selector can return null, and attaching a listener to that value will fail. A stylesheet can hide the message even when JavaScript updated it correctly. The console and element inspector answer different questions. Change one suspected cause, repeat the same steps, and verify the outcome.`,`Before sharing, try a narrow screen, keyboard navigation, and enlarged text. Look for clipped controls and missing focus indicators. These checks are part of whether the page works for people. A page is ready when its essential activity remains understandable and usable under realistic conditions.`]}],exercise:['Add a second button that restores the original message.','Explain what happens after a refresh and why.','Sketch the request and response needed for a real reservation.'],answer:'The reset button can assign the original string to message.textContent. A refresh loads the initial document because this example stores no persistent state. A real reservation needs a server to check permission and availability before storing the result.',glossary:[['Frontend','The interface and browser-side behavior presented to a user.'],['Backend','Server-side logic that receives requests and applies rules.'],['DNS','A system that resolves names to records, including addressing information.'],['State','Information describing the current condition of an application.']],sources:[{title:'MDN: Learn web development',url:'https://developer.mozilla.org/en-US/docs/Learn_web_development'},{title:'MDN: How the Internet works',url:'https://developer.mozilla.org/en-US/docs/Learn_web_development/Howto/Web_mechanics/How_does_the_Internet_work'}]});
guides.push({slug:'python-problem-solving',title:'Think like a programmer: a practical Python guide',category:'Programming',summary:'Turn a real problem into inputs, rules, functions, and tests using a small study planner.',goals:['Translate requirements into clear rules','Write a function with input validation','Test boundaries and explain the result'],sections:[
{id:'problem',title:'1. Describe the problem before the code',paragraphs:[`Suppose you have several lessons to study and want to spread them across the days before an exam. A first program can calculate a suggested number of lessons per day. Before opening an editor, define the question: given a nonnegative whole number of lessons and a positive whole number of days, what whole-number daily target is sufficient to cover the lessons?`,`There are hidden choices. Are partial lessons allowed? Does the program promise the same workload every day? What happens when there are no lessons or zero days? Our version returns a target rounded upward; it does not produce a complete schedule or estimate lesson difficulty. Those limits help keep the first solution honest.`,`Write three examples by hand: 12 lessons over 4 days gives 3; 13 lessons over 4 days gives 4; zero lessons over 4 days gives 0. These are small enough to check without software. They will become tests once the function exists.`]},
{id:'data',title:'2. Choose data that matches the meaning',paragraphs:[`A variable associates a name with a value. Good names connect a calculation to its requirement. lessons and days are more useful here than x and y. An integer represents a whole-number count. A string represents text, even when its characters look numeric. That distinction matters when accepting input from a person or a file.`,`Keep the boundary between input collection and calculation visible. A text field might contain spaces, an empty string, or a sentence. The calculation should not silently guess what those values mean. A surrounding interface can ask the user to correct input before passing validated values to the function.`,`Think about units as well as types. A variable called time could mean days, minutes, or seconds. Naming it days makes an accidental unit conversion easier to notice. Many bugs arise when two pieces of code agree on a type while disagreeing about what the value represents.`]},
{id:'function',title:'3. Put one rule in one function',paragraphs:[`The function below accepts two values and returns the daily target. Integer arithmetic avoids introducing floating-point rounding for this whole-number problem. Adding days minus one before integer division rounds upward for the nonnegative lesson counts allowed by the validation.`,`The checks deliberately reject booleans as well as fractional numbers. Python treats bool as a subclass of int, so a plain isinstance check would accept True as an integer. This example chooses strict built-in integer inputs to match its specification. That is a local design choice, not a requirement for every Python program.`,`Returning a value and printing it are different actions. A returned value can be reused, tested, or displayed in a graphical interface. Printing writes a representation for a person to see. Keeping calculation separate from display makes a function easier to compose with other parts of a program.`],language:'Python 3',code:`def daily_target(lessons, days):
    if type(lessons) is not int or type(days) is not int:
        raise TypeError("Lessons and days must be whole numbers")
    if lessons < 0:
        raise ValueError("Lessons cannot be negative")
    if days <= 0:
        raise ValueError("Days must be greater than zero")
    return (lessons + days - 1) // days

print(daily_target(13, 4))  # 4`},
{id:'flow',title:'4. Follow execution one step at a time',paragraphs:[`Conditions let a program choose a path. Invalid values cause an exception before this calculation. Valid values reach the return statement. Trace daily_target(13, 4) on paper: both values are integers; thirteen is not negative; four is positive; the expression evaluates to sixteen divided by four using integer division.`,`A loop repeats work. To compare several deadlines, call the same function for each candidate number of days rather than copying the formula. Keeping the rule in one function means every comparison follows the same behavior. Repeated copies of a formula create opportunities for one version to drift away from the others.`,`When tracing becomes difficult, reduce the input. Use two candidate deadlines rather than two hundred. Observe values at the start of each iteration. Build a reliable explanation of the output instead of merely finding a change that makes an error disappear.`],language:'Python 3',code:`for available_days in [3, 4, 7]:
    target = daily_target(13, available_days)
    print(f"{available_days} days: {target} lessons per day")`},
{id:'testing',title:'5. Test the boundaries that define the rule',paragraphs:[`Ordinary cases are useful, but boundaries expose incomplete rules. Zero lessons should work because there is nothing to cover. One day should require all remaining lessons. Zero days should fail because there is no valid study period. A negative count should fail because it does not represent the problem we defined.`,`These assertions are lightweight learning checks. A failed assertion interrupts execution and points to a mismatch. Run them after the function definition in a local Python file. A maintained project can use a test framework to organize more cases and provide clearer reports.`,`Tests should explain meaningful behavior. Checking only that the function returns an integer would miss a target too small to finish the lessons. Check expected results and rejected inputs. When you find a bug, add a case that exposes that mistake so it is less likely to return unnoticed.`],language:'Python 3',code:`assert daily_target(12, 4) == 3
assert daily_target(13, 4) == 4
assert daily_target(0, 4) == 0
assert daily_target(9, 1) == 9

try:
    daily_target(4, 0)
except ValueError:
    pass
else:
    raise AssertionError("Zero days should be rejected")`},
{id:'growth',title:'6. Grow the program without losing its meaning',paragraphs:[`The target is conservative. Thirteen lessons over four days yields four, but doing four each day would exceed thirteen. A complete schedule could distribute workloads as four, three, three, and three. This is a different output with a different promise. Treat it as a new requirement instead of quietly changing the existing function's meaning.`,`Another extension is lesson duration. A short revision topic and a long practical lab should not automatically have the same weight. Represent each lesson with a title and estimated minutes, then allocate time instead of counts. Decide whether a lesson can be split and how to handle an impossible schedule before writing code.`,`Keep calculations separate from presentation and storage. A function receiving and returning plain data is straightforward to test. An interface can collect inputs, display results, and explain errors. You can improve that interface without rewriting the study rule.`,`Practice deliberate decomposition: describe a task, choose meaningful data, isolate a rule, verify examples, and then connect more parts. You do not need every language feature to solve useful problems. You need reliable building blocks and the ability to explain why your solution satisfies its requirement.`]}],exercise:['Predict the result for 17 lessons over 5 days.','Test negative lessons, a fractional day count, and a boolean.','Design a separate function returning exact daily workloads.'],answer:'The target for 17 lessons over 5 days is 4. For an exact schedule, divide lessons into a quotient and remainder. Give one extra lesson to the first remainder days. Verify that the list has the requested length and its sum equals the lesson count.',glossary:[['Function','A named block of code that accepts inputs and can return a result.'],['Exception','A signal that interrupts normal execution when a problem occurs.'],['Boundary case','An input near the edge of allowed behavior.'],['Specification','An explicit description of required program behavior.']],sources:[{title:'Python tutorial',url:'https://docs.python.org/3/tutorial/'},{title:'Python: Control flow and functions',url:'https://docs.python.org/3/tutorial/controlflow.html'}]});
guides.push({slug:'git-team-workflow',title:'Git without guesswork: a workflow for real projects',category:'Developer workflow',summary:'Understand working files, staging, commits, and branches through a focused documentation change.',goals:['Explain what a commit contains','Review a change before recording it','Use a branch and resolve conflicts thoughtfully'],sections:[
{id:'history',title:'1. Treat history as a record of decisions',paragraphs:[`Imagine maintaining a club website with two classmates. One edits the event schedule, another updates joining instructions, and you improve the contact page. A folder of files named final, final2, and final-really-final does not explain which changes belong together. Git records project states and their relationships. Good history makes a change understandable to someone absent when it was made.`,`A useful commit answers what changed and why. “Fix stuff” tells a future reader almost nothing. “Clarify the joining deadline for new members” gives a purpose that can be compared with the actual differences. The message does not replace reviewing the code, but it provides context.`,`Start with a small, complete change. A documentation correction is a better first exercise than simultaneously redesigning a site, updating dependencies, and reorganizing every folder. Smaller changes reduce the possible causes when something later behaves differently.`]},
{id:'areas',title:'2. Distinguish files, staging, and history',paragraphs:[`The working tree contains the files you edit. The staging area describes changes selected for the next commit. A commit records the staged state with metadata and links to parent history. Editing does not automatically stage a file, and staging does not publish it to other people.`,`This separation helps when an editing session produces unrelated changes. Record a corrected deadline first and a separate design improvement later. Before committing, examine both the unstaged and staged differences. They answer different questions: what remains outside the next commit, and what is about to be included?`,`Replace README.md below with the file you changed. These commands assume Git is installed and you are inside a repository. They inspect the current state, select a file, and inspect the selected difference. Pause and read that difference before committing.`],language:'Terminal',code:`git status
git diff
git add README.md
git diff --staged
git commit -m "Clarify the club joining deadline"`},
{id:'branch',title:'3. Name a focused line of work',paragraphs:[`A branch gives a movable name to a line of history. It lets you develop a focused change while keeping the project's main line understandable. Creating a branch does not make an independent disk copy of every file. The working tree reflects the checked-out branch and state, subject to uncommitted changes.`,`Before starting, inspect git status and understand existing edits. Agree on a starting branch and synchronization procedure in shared projects. Not every repository calls its main branch main. Switching branches is not a way to make unrelated edits disappear safely.`,`The example creates a branch for one documentation task. After committing, read the short history and confirm the new commit appears where expected. A branch name should describe the work well enough that a teammate can distinguish it from other ongoing tasks.`],language:'Terminal',code:`git status
git switch -c docs/joining-deadline
# Edit, review, stage, and commit the intended change.
git log --oneline -5`},
{id:'review',title:'4. Review as a future maintainer',paragraphs:[`A review is a structured attempt to understand a change, not just a search for punctuation mistakes. Ask whether the change solves the stated problem, whether adjacent behavior still works, and whether the implementation introduces a new assumption. For a deadline correction, check every place users encounter the date. For code, follow the affected data through its relevant paths.`,`Explain how you verified the result. “Checked the joining page at narrow width and followed the form link” is more useful than an unexplained “tested.” Choose evidence proportional to the change. A paragraph edit usually needs no new automated test; a calculation used throughout an application probably does.`,`Keep generated files, credentials, and unrelated formatting changes out of a review unless they belong to the task. An accidental long diff makes important changes harder to judge. Investigate unexpected files before including them. A clean review lets someone concentrate on the actual decision.`]},
{id:'conflicts',title:'5. Resolve conflicts by preserving intent',paragraphs:[`A conflict means Git could not automatically reconcile competing changes. It does not mean one contributor is wrong. One classmate might correct a meeting time while another rewrites the same sentence. The result may need both the new time and clearer wording. Mechanically choosing an entire side can discard valid work.`,`Read surrounding content and understand each change's purpose. Edit the intended final version, remove conflict markers, and review it. Stage the resolution and follow the instructions displayed by git status for the operation in progress. Merge and rebase continuation workflows differ, so the same final command does not fit every situation.`,`If the intended outcome is unclear, ask about the requirement. For code, run relevant checks after resolving the conflict. A file without conflict markers can still contain a logical mistake. Mechanical completion means Git can record the result; it does not prove the application behaves correctly.`]},
{id:'recovery',title:'6. Recover deliberately and collaborate clearly',paragraphs:[`Before undoing anything, identify the state you want to change: staging, working files, or committed history. To remove a file from staging while keeping its edits, git restore --staged README.md is useful in a repository with a commit to restore from. It changes the proposed commit rather than erasing editing work.`,`Restoring a working file can discard uncommitted edits. Read command documentation and inspect status before recovery. Do not paste a destructive command from an unrelated troubleshooting answer. If uncertain, preserve a copy of affected work and investigate with read-only commands.`,`A remote is a destination for exchanging Git history. Committing locally and pushing are separate actions. Your team may use a pull request or merge request before changes reach the main line. Agree on naming, review expectations, and merge ownership to make collaboration predictable.`,`Git works best as a communication tool. Keep changes focused, explain their purpose, review what you stage, and verify the integrated result. Aim for history that helps someone reason about the project months later, when nobody remembers every detail of the original task.`]}],exercise:['Create a practice repository and commit a short README.','Edit two sentences, stage the file, and compare git diff with git diff --staged.','Unstage the file and confirm that your edits remain.'],answer:'After staging all edits, git diff normally shows no unstaged difference while git diff --staged shows the selected changes. In the practice repository, git restore --staged README.md removes that selection but keeps the working file edited. Verify with status and diff.',glossary:[['Working tree','The checked-out files you edit.'],['Staging area','The proposed content of the next commit.'],['Commit','A recorded project state linked to its parent history.'],['Conflict','A change combination requiring a person to choose the intended result.']],sources:[{title:'Git reference',url:'https://git-scm.com/docs'},{title:'Git: commit',url:'https://git-scm.com/docs/git-commit'},{title:'Git: switch',url:'https://git-scm.com/docs/git-switch'},{title:'Git: restore',url:'https://git-scm.com/docs/git-restore'}]});
guides.push({slug:'apis-and-json',title:'APIs and JSON: build a reliable data conversation',category:'Backend & APIs',summary:'Design a small task API, read responses safely, and handle loading, empty, and failure states.',goals:['Describe an API contract','Distinguish parsing from validation','Handle HTTP errors and unexpected data'],sections:[
{id:'contract',title:'1. Define the conversation',paragraphs:[`An application programming interface defines how software interacts with another component. In a web application, an HTTP API often lets a browser request data or ask a server to perform an operation. A caller works with a documented contract instead of knowing every implementation detail.`,`Consider a student task board. The browser needs tasks with an identifier, title, and completion flag. That shape is only the beginning. The contract should state which requests are allowed, how permission is checked, what happens when no tasks exist, and how errors are represented.`,`Write example requests and responses before implementing both sides. An example may reveal that the frontend expects an array while the backend returns an object containing an array. Finding the mismatch on paper is cheaper than debugging two running applications. The API in this guide is hypothetical; DevShelf does not provide these endpoints.`]},
{id:'json',title:'2. Read JSON as structured data',paragraphs:[`JSON represents objects, arrays, strings, numbers, booleans, and null. An object groups named values; an array represents an ordered collection. Here tasks is an array because several tasks may exist, and each task is an object whose fields describe a record. Property names and string values use double quotes.`,`A parser checks JSON syntax. It does not prove that the result matches application expectations. The text 42 is valid JSON but is not the task-list response below. An object with a tasks property might still contain wrong field types. Keep syntax checking separate from application validation.`,`Use the DevShelf formatter to expand and minify the example. Whitespace changes while the intended data model stays the same. Remove a required quote and observe the error. Then change done from false to the string "false". This remains valid JSON but changes the field's meaning and type.`],language:'JSON',code:`{
  "tasks": [
    { "id": "task-1", "title": "Review networking notes", "done": false },
    { "id": "task-2", "title": "Practice Python functions", "done": true }
  ]
}`},
{id:'http',title:'3. Distinguish response outcomes',paragraphs:[`An HTTP response contains a status and may include headers and a body. A successful request can return an empty collection. A failed request might return structured error data or an HTML page generated by infrastructure. Do not assume every response has the JSON shape expected for success.`,`An empty tasks array is normal for our task board. The interface can explain that no tasks have been added. A permission failure needs a different response, such as asking the user to sign in when appropriate. A server failure should never be presented as an empty list, because that falsely suggests existing tasks disappeared.`,`Sketch loading, populated, empty, and error states separately. Decide whether previous results stay visible during refresh, where retry controls belong, and whether the action is safe to repeat. The user needs to distinguish having no information from waiting for information or failing to retrieve it.`]},
{id:'fetch',title:'4. Request and validate data',paragraphs:[`Browser fetch returns a response for HTTP error statuses such as 404, so check response.ok rather than relying only on promise rejection. Reading with response.json is asynchronous and can fail if the content is not JSON. The function below handles these stages explicitly.`,`After parsing, validate the fields your application needs. Here tasks must be an array, and every item must contain expected primitive fields. A larger application may use a schema library for nested data or shared contracts. The principle is the same: received data is not automatically valid application data.`,`Run this example only in a project with a matching /api/tasks endpoint. It is an integration example, not a live public service. A caller should catch failures and show a useful error rather than leaving an unhandled promise rejection in the console.`],language:'JavaScript',code:`async function loadTasks() {
  const response = await fetch('/api/tasks', {
    headers: { Accept: 'application/json' }
  });
  if (!response.ok) {
    throw new Error('Task request failed: ' + response.status);
  }
  const data = await response.json();
  if (!data || !Array.isArray(data.tasks)) {
    throw new Error('Expected a tasks array');
  }
  const valid = data.tasks.every(task =>
    task !== null && typeof task === 'object' &&
    typeof task.id === 'string' &&
    typeof task.title === 'string' &&
    typeof task.done === 'boolean'
  );
  if (!valid) throw new Error('Unexpected task data');
  return data.tasks;
}`},
{id:'writes',title:'5. Design changes and permissions together',paragraphs:[`Reading and changing tasks have different consequences. Define what a write operation accepts and who may perform it. Hiding a button is not access control: a caller can construct a request outside the interface. The server owning the data must enforce permission for the operation.`,`A completion request also raises timing questions. What if the user clicks twice? What if the request succeeds but its response is lost? What if another device changes the task? Explicitly setting done to true can be easier to reason about than blindly toggling it with every repeated request. The API's documented semantics determine the right approach.`,`Keep private service credentials on the server when required by the design. A value sent to browser JavaScript is available to the browser's user. Renaming it or using Base64 does not make it secret. Base64 is a representation format, not encryption. This distinction matters when a local exercise becomes a shared application.`]},
{id:'diagnose',title:'6. Diagnose failure systematically',paragraphs:[`Inspect the request URL, method, status, and response body in the Network panel. Compare them with the contract. Did the frontend call the wrong path? Did the server return an error object or HTML? Gather observations before changing code. Separate routing problems from parsing and permission problems.`,`Browser cross-origin rules can prevent a page from reading another origin's response unless the server permits the interaction. Switching fetch to no-cors is not a general fix for reading blocked JSON; an opaque response is not normally readable. Use supported server configuration or an appropriate backend integration.`,`Test an empty array, a missing field, a wrong type, an HTTP error, and invalid JSON. Consider overlapping searches: an older response should not unexpectedly replace a newer result. Cancellation or request tracking may be appropriate depending on the interface.`,`Reliable API integration rests on explicit agreements. The caller requests a defined operation, the server verifies and performs it, and the interface communicates the outcome honestly. When these agreements are visible, testing and debugging become systematic instead of a sequence of guesses.`]}],exercise:['Introduce a syntax error in the example JSON and inspect the formatter result.','Change a completion flag into a string and explain why parsing does not reject it.','Write different interface messages for loading, empty data, and failure.'],answer:'Missing quotes should cause a parsing error. A string-valued flag remains valid JSON but violates the expected schema. Use distinct messages such as “Loading tasks,” “No tasks yet,” and “Could not load tasks—try again” so a failed request is never mistaken for an empty account.',glossary:[['API contract','The agreement about requests, responses, and behavior.'],['JSON','A text format for structured data.'],['Validation','Checking whether data satisfies application rules.'],['HTTP status','A code describing an HTTP request outcome.']],sources:[{title:'MDN: HTTP overview',url:'https://developer.mozilla.org/en-US/docs/Web/HTTP/Guides/Overview'},{title:'MDN: Using Fetch',url:'https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch'}]});
