export type Section={id:string,title:string,paragraphs:string[],code?:string,language?:string};
export type Guide={slug:string,title:string,category:string,summary:string,goals:string[],sections:Section[],exercise:string[],answer:string,glossary:[string,string][],sources:{title:string,url:string}[]};
export const guides:Guide[]=[];
export function guideWords(g:Guide){return [g.title,g.summary,...g.goals,...g.sections.flatMap(s=>[s.title,...s.paragraphs]),...g.exercise,g.answer,...g.glossary.flat()].join(' ').split(/\s+/).length}
export function readingTime(g:Guide){return Math.ceil(guideWords(g)/180)}
guides.push({slug:'how-websites-work',title:'How websites work: from a click to a complete page',category:'Web foundations',summary:'Follow a browser request, understand the frontend and backend, and build a small page you can explain line by line.',goals:['Explain the browser–server relationship','Separate HTML, CSS, and JavaScript responsibilities','Build and troubleshoot a small interactive page'],sections:[
{id:'big-picture',title:'1. Start with the whole system',paragraphs:[`Imagine a school library website. A student wants to find a book, see whether a copy is available, and reserve it. On screen, this looks like a search field and a few buttons. Behind that interaction are separate responsibilities: showing the interface, receiving requests, applying borrowing rules, and keeping records. Learning web development becomes easier when you can name these responsibilities before choosing a framework.`,`The frontend is the part presented through the browser. The backend handles work on the server, such as deciding whether a reservation is allowed. A database keeps information that needs to survive beyond a single request. These are roles, not necessarily separate computers. A small project might place several roles together. A larger project might distribute them. Ask where each piece of work happens and which component owns each decision.`,`Draw three boxes: browser, application server, and database. Draw an arrow for a search request and another for its result. Label what travels on each arrow. This simple drawing can reveal missing assumptions more quickly than writing another component.`]},
{id:'journey',title:'2. Follow one request',paragraphs:[`When you enter a website address, the browser needs a way to reach the appropriate service. DNS helps resolve a hostname to addressing information. Network connections carry requests and responses; HTTPS adds protection through TLS. The browser requests a resource, and a server sends a response. Some responses contain HTML, while others contain an image, stylesheet, or data. Caches may satisfy some requests without contacting the original server.`,`Separate an address from a resource. In https://example.com/books, the hostname is example.com and the path is /books. The same host can provide many resources. A successful connection does not mean every path exists, and a working homepage does not prove that the search endpoint works. Each request has its own outcome.`,`Open your browser's developer tools and choose Network. Reload a page and observe the requests. Pick one document, one image, and one stylesheet. Compare their types and sizes. Do not worry about memorizing every column. Connect visible content to a real transfer instead of treating the entire page as one mysterious object.`]},
{id:'languages',title:'3. Give each language a clear job',paragraphs:[`HTML describes structure and meaning. A heading communicates hierarchy; a button communicates an action. CSS controls presentation, including spacing, color, layout, and adaptation to available space. JavaScript handles behavior such as reacting to a click or updating a result. The layers work together, but they should not obscure one another.`,`Consider a borrowing form. The label and input belong in HTML, the spacing belongs in CSS, and the response to submission belongs in JavaScript. If the page is unreadable until a script runs, ask whether essential content can be expressed in HTML first. If a clickable element is an action, start with a button so keyboard behavior comes with the correct element.`,`These boundaries help debugging. An item in the wrong position suggests a layout problem. A button that looks right but does nothing suggests an event or logic problem. Missing content suggests a rendering or data problem. This is a starting hypothesis, not a guarantee, but it gives your investigation direction.`]},
{id:'build',title:'4. Build a tiny interactive page',paragraphs:[`Save this example as index.html and open it in a browser. It has one job: update a message when a button is pressed. Keeping the exercise small makes it possible to understand every line. You do not need a database, package manager, or deployment service to learn this interaction.`,`The script appears after the elements it selects, so they exist when it runs. textContent updates plain text rather than interpreting the value as HTML. The status region helps announce the changed message to assistive technology. After clicking, use the Tab key to focus the button and activate it with the keyboard.`,`Modify the message, change the button label, and adjust the maximum width. Make one change at a time and predict its effect before reloading. Prediction turns copying into understanding. If the result differs, inspect the relevant element or read the console rather than randomly changing several lines.`],language:'HTML',code:`<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Library welcome</title>
  <style>
    body { font: 1rem/1.6 system-ui; max-width: 42rem; margin: 3rem auto; padding: 1rem; }
    button { font: inherit; padding: .7rem 1rem; }
  </style>
</head>
<body>
  <h1>Welcome to the library</h1>
  <p id="message" role="status">Ready to find your next book?</p>
  <button id="start" type="button">Start exploring</button>
  <script>
    const button = document.querySelector('#start');
    const message = document.querySelector('#message');
    button.addEventListener('click', () => {
      message.textContent = 'Choose a subject to learn today.';
    });
  </script>
</body>
</html>`},
{id:'state',title:'5. Understand what survives a reload',paragraphs:[`The message is temporary browser state. Refreshing restores its original value. A real reservation needs a durable record. The server should verify the user, check availability, and write a reservation to persistent storage. Showing a success message is not itself proof that a reservation was saved.`,`Imagine two students reserving the last copy at nearly the same time. A browser-only availability check can become outdated between viewing and submitting. The system that owns the record must enforce the rule when the change occurs. Interfaces can offer helpful early validation while the backend remains responsible for authoritative decisions.`,`For each feature, write down what the user sees, what the server must confirm, and what must be stored. Consider how the page behaves if the request fails. A useful error should preserve the student's input and explain a next action.`]},
{id:'debug',title:'6. Debug with evidence',paragraphs:[`Describe the failure precisely. “The page is broken” is difficult to investigate. “The button receives focus but the message never changes after activation” is more useful. Record expected behavior, actual behavior, and reproduction steps. Inspect the smallest relevant part of the system.`,`A misspelled selector can return null, and attaching a listener to that value will fail. A stylesheet can hide the message even when JavaScript updated it correctly. The console and element inspector answer different questions. Change one suspected cause, repeat the same steps, and verify the outcome.`,`Before sharing, try a narrow screen, keyboard navigation, and enlarged text. Look for clipped controls and missing focus indicators. These checks are part of whether the page works for people. A page is ready when its essential activity remains understandable and usable under realistic conditions.`]}],exercise:['Add a second button that restores the original message.','Explain what happens after a refresh and why.','Sketch the request and response needed for a real reservation.'],answer:'The reset button can assign the original string to message.textContent. A refresh loads the initial document because this example stores no persistent state. A real reservation needs a server to check permission and availability before storing the result.',glossary:[['Frontend','The interface and browser-side behavior presented to a user.'],['Backend','Server-side logic that receives requests and applies rules.'],['DNS','A system that resolves names to records, including addressing information.'],['State','Information describing the current condition of an application.']],sources:[{title:'MDN: Learn web development',url:'https://developer.mozilla.org/en-US/docs/Learn_web_development'},{title:'MDN: How the Internet works',url:'https://developer.mozilla.org/en-US/docs/Learn_web_development/Howto/Web_mechanics/How_does_the_Internet_work'}]});
guides.push({slug:'python-problem-solving',title:'Think like a programmer: a practical Python guide',category:'Programming',summary:'Turn a real problem into inputs, rules, functions, and tests using a small study planner.',goals:['Translate requirements into clear rules','Write a function with input validation','Test boundaries and explain the result'],sections:[
{id:'problem',title:'1. Describe the problem before the code',paragraphs:[`Suppose you have several lessons to study and want to spread them across the days before an exam. A first program can calculate a suggested number of lessons per day. Before opening an editor, define the question: given a nonnegative whole number of lessons and a positive whole number of days, what whole-number daily target is sufficient to cover the lessons?`,`There are hidden choices. Are partial lessons allowed? Does the program promise the same workload every day? What happens when there are no lessons or zero days? Our version returns a target rounded upward; it does not produce a complete schedule or estimate lesson difficulty. Those limits help keep the first solution honest.`,`Write three examples by hand: 12 lessons over 4 days gives 3; 13 lessons over 4 days gives 4; zero lessons over 4 days gives 0. These are small enough to check without software. They will become tests once the function exists.`]},
{id:'data',title:'2. Choose data that matches the meaning',paragraphs:[`A variable associates a name with a value. Good names connect a calculation to its requirement. lessons and days are more useful here than x and y. An integer represents a whole-number count. A string represents text, even when its characters look numeric. That distinction matters when accepting input from a person or a file.`,`Keep the boundary between input collection and calculation visible. A text field might contain spaces, an empty string, or a sentence. The calculation should not silently guess what those values mean. A surrounding interface can ask the user to correct input before passing validated values to the function.`,`Think about units as well as types. A variable called time could mean days, minutes, or seconds. Naming it days makes an accidental unit conversion easier to notice. Many bugs arise when two pieces of code agree on a type while disagreeing about what the value represents.`]},
{id:'function',title:'3. Put one rule in one function',paragraphs:[`The function below accepts two values and returns the daily target. Integer arithmetic avoids introducing floating-point rounding for this whole-number problem. Adding days minus one before integer division rounds upward for the nonnegative lesson counts allowed by the validation.`,`The checks deliberately reject booleans as well as fractional numbers. Python treats bool as a subclass of int, so a plain isinstance check would accept True as an integer. This example chooses strict built-in integer inputs to match its specification. That is a local design choice, not a requirement for every Python program.`,`Returning a value and printing it are different actions. A returned value can be reused, tested, or displayed in a graphical interface. Printing writes a representation for a person to see. Keeping calculation separate from display makes a function easier to compose with other parts of a program.`],language:'Python 3',code:`def daily_target(lessons, days):
    if type(lessons) is not int or type(days) is not int:
        raise TypeError("Lessons and days must be whole numbers")
    if lessons < 0:
        raise ValueError("Lessons cannot be negative")
    if days <= 0:
        raise ValueError("Days must be greater than zero")
    return (lessons + days - 1) // days

print(daily_target(13, 4))  # 4`},
{id:'flow',title:'4. Follow execution one step at a time',paragraphs:[`Conditions let a program choose a path. Invalid values cause an exception before this calculation. Valid values reach the return statement. Trace daily_target(13, 4) on paper: both values are integers; thirteen is not negative; four is positive; the expression evaluates to sixteen divided by four using integer division.`,`A loop repeats work. To compare several deadlines, call the same function for each candidate number of days rather than copying the formula. Keeping the rule in one function means every comparison follows the same behavior. Repeated copies of a formula create opportunities for one version to drift away from the others.`,`When tracing becomes difficult, reduce the input. Use two candidate deadlines rather than two hundred. Observe values at the start of each iteration. Build a reliable explanation of the output instead of merely finding a change that makes an error disappear.`],language:'Python 3',code:`for available_days in [3, 4, 7]:
    target = daily_target(13, available_days)
    print(f"{available_days} days: {target} lessons per day")`},
{id:'testing',title:'5. Test the boundaries that define the rule',paragraphs:[`Ordinary cases are useful, but boundaries expose incomplete rules. Zero lessons should work because there is nothing to cover. One day should require all remaining lessons. Zero days should fail because there is no valid study period. A negative count should fail because it does not represent the problem we defined.`,`These assertions are lightweight learning checks. A failed assertion interrupts execution and points to a mismatch. Run them after the function definition in a local Python file. A maintained project can use a test framework to organize more cases and provide clearer reports.`,`Tests should explain meaningful behavior. Checking only that the function returns an integer would miss a target too small to finish the lessons. Check expected results and rejected inputs. When you find a bug, add a case that exposes that mistake so it is less likely to return unnoticed.`],language:'Python 3',code:`assert daily_target(12, 4) == 3
assert daily_target(13, 4) == 4
assert daily_target(0, 4) == 0
assert daily_target(9, 1) == 9

try:
    daily_target(4, 0)
except ValueError:
    pass
else:
    raise AssertionError("Zero days should be rejected")`},
{id:'growth',title:'6. Grow the program without losing its meaning',paragraphs:[`The target is conservative. Thirteen lessons over four days yields four, but doing four each day would exceed thirteen. A complete schedule could distribute workloads as four, three, three, and three. This is a different output with a different promise. Treat it as a new requirement instead of quietly changing the existing function's meaning.`,`Another extension is lesson duration. A short revision topic and a long practical lab should not automatically have the same weight. Represent each lesson with a title and estimated minutes, then allocate time instead of counts. Decide whether a lesson can be split and how to handle an impossible schedule before writing code.`,`Keep calculations separate from presentation and storage. A function receiving and returning plain data is straightforward to test. An interface can collect inputs, display results, and explain errors. You can improve that interface without rewriting the study rule.`,`Practice deliberate decomposition: describe a task, choose meaningful data, isolate a rule, verify examples, and then connect more parts. You do not need every language feature to solve useful problems. You need reliable building blocks and the ability to explain why your solution satisfies its requirement.`]}],exercise:['Predict the result for 17 lessons over 5 days.','Test negative lessons, a fractional day count, and a boolean.','Design a separate function returning exact daily workloads.'],answer:'The target for 17 lessons over 5 days is 4. For an exact schedule, divide lessons into a quotient and remainder. Give one extra lesson to the first remainder days. Verify that the list has the requested length and its sum equals the lesson count.',glossary:[['Function','A named block of code that accepts inputs and can return a result.'],['Exception','A signal that interrupts normal execution when a problem occurs.'],['Boundary case','An input near the edge of allowed behavior.'],['Specification','An explicit description of required program behavior.']],sources:[{title:'Python tutorial',url:'https://docs.python.org/3/tutorial/'},{title:'Python: Control flow and functions',url:'https://docs.python.org/3/tutorial/controlflow.html'}]});
guides.push({slug:'git-team-workflow',title:'Git without guesswork: a workflow for real projects',category:'Developer workflow',summary:'Understand working files, staging, commits, and branches through a focused documentation change.',goals:['Explain what a commit contains','Review a change before recording it','Use a branch and resolve conflicts thoughtfully'],sections:[
{id:'history',title:'1. Treat history as a record of decisions',paragraphs:[`Imagine maintaining a club website with two classmates. One edits the event schedule, another updates joining instructions, and you improve the contact page. A folder of files named final, final2, and final-really-final does not explain which changes belong together. Git records project states and their relationships. Good history makes a change understandable to someone absent when it was made.`,`A useful commit answers what changed and why. “Fix stuff” tells a future reader almost nothing. “Clarify the joining deadline for new members” gives a purpose that can be compared with the actual differences. The message does not replace reviewing the code, but it provides context.`,`Start with a small, complete change. A documentation correction is a better first exercise than simultaneously redesigning a site, updating dependencies, and reorganizing every folder. Smaller changes reduce the possible causes when something later behaves differently.`]},
{id:'areas',title:'2. Distinguish files, staging, and history',paragraphs:[`The working tree contains the files you edit. The staging area describes changes selected for the next commit. A commit records the staged state with metadata and links to parent history. Editing does not automatically stage a file, and staging does not publish it to other people.`,`This separation helps when an editing session produces unrelated changes. Record a corrected deadline first and a separate design improvement later. Before committing, examine both the unstaged and staged differences. They answer different questions: what remains outside the next commit, and what is about to be included?`,`Replace README.md below with the file you changed. These commands assume Git is installed and you are inside a repository. They inspect the current state, select a file, and inspect the selected difference. Pause and read that difference before committing.`],language:'Terminal',code:`git status
git diff
git add README.md
git diff --staged
git commit -m "Clarify the club joining deadline"`},
{id:'branch',title:'3. Name a focused line of work',paragraphs:[`A branch gives a movable name to a line of history. It lets you develop a focused change while keeping the project's main line understandable. Creating a branch does not make an independent disk copy of every file. The working tree reflects the checked-out branch and state, subject to uncommitted changes.`,`Before starting, inspect git status and understand existing edits. Agree on a starting branch and synchronization procedure in shared projects. Not every repository calls its main branch main. Switching branches is not a way to make unrelated edits disappear safely.`,`The example creates a branch for one documentation task. After committing, read the short history and confirm the new commit appears where expected. A branch name should describe the work well enough that a teammate can distinguish it from other ongoing tasks.`],language:'Terminal',code:`git status
git switch -c docs/joining-deadline
# Edit, review, stage, and commit the intended change.
git log --oneline -5`},
{id:'review',title:'4. Review as a future maintainer',paragraphs:[`A review is a structured attempt to understand a change, not just a search for punctuation mistakes. Ask whether the change solves the stated problem, whether adjacent behavior still works, and whether the implementation introduces a new assumption. For a deadline correction, check every place users encounter the date. For code, follow the affected data through its relevant paths.`,`Explain how you verified the result. “Checked the joining page at narrow width and followed the form link” is more useful than an unexplained “tested.” Choose evidence proportional to the change. A paragraph edit usually needs no new automated test; a calculation used throughout an application probably does.`,`Keep generated files, credentials, and unrelated formatting changes out of a review unless they belong to the task. An accidental long diff makes important changes harder to judge. Investigate unexpected files before including them. A clean review lets someone concentrate on the actual decision.`]},
{id:'conflicts',title:'5. Resolve conflicts by preserving intent',paragraphs:[`A conflict means Git could not automatically reconcile competing changes. It does not mean one contributor is wrong. One classmate might correct a meeting time while another rewrites the same sentence. The result may need both the new time and clearer wording. Mechanically choosing an entire side can discard valid work.`,`Read surrounding content and understand each change's purpose. Edit the intended final version, remove conflict markers, and review it. Stage the resolution and follow the instructions displayed by git status for the operation in progress. Merge and rebase continuation workflows differ, so the same final command does not fit every situation.`,`If the intended outcome is unclear, ask about the requirement. For code, run relevant checks after resolving the conflict. A file without conflict markers can still contain a logical mistake. Mechanical completion means Git can record the result; it does not prove the application behaves correctly.`]},
{id:'recovery',title:'6. Recover deliberately and collaborate clearly',paragraphs:[`Before undoing anything, identify the state you want to change: staging, working files, or committed history. To remove a file from staging while keeping its edits, git restore --staged README.md is useful in a repository with a commit to restore from. It changes the proposed commit rather than erasing editing work.`,`Restoring a working file can discard uncommitted edits. Read command documentation and inspect status before recovery. Do not paste a destructive command from an unrelated troubleshooting answer. If uncertain, preserve a copy of affected work and investigate with read-only commands.`,`A remote is a destination for exchanging Git history. Committing locally and pushing are separate actions. Your team may use a pull request or merge request before changes reach the main line. Agree on naming, review expectations, and merge ownership to make collaboration predictable.`,`Git works best as a communication tool. Keep changes focused, explain their purpose, review what you stage, and verify the integrated result. Aim for history that helps someone reason about the project months later, when nobody remembers every detail of the original task.`]}],exercise:['Create a practice repository and commit a short README.','Edit two sentences, stage the file, and compare git diff with git diff --staged.','Unstage the file and confirm that your edits remain.'],answer:'After staging all edits, git diff normally shows no unstaged difference while git diff --staged shows the selected changes. In the practice repository, git restore --staged README.md removes that selection but keeps the working file edited. Verify with status and diff.',glossary:[['Working tree','The checked-out files you edit.'],['Staging area','The proposed content of the next commit.'],['Commit','A recorded project state linked to its parent history.'],['Conflict','A change combination requiring a person to choose the intended result.']],sources:[{title:'Git reference',url:'https://git-scm.com/docs'},{title:'Git: commit',url:'https://git-scm.com/docs/git-commit'},{title:'Git: switch',url:'https://git-scm.com/docs/git-switch'},{title:'Git: restore',url:'https://git-scm.com/docs/git-restore'}]});
guides.push({slug:'apis-and-json',title:'APIs and JSON: build a reliable data conversation',category:'Backend & APIs',summary:'Design a small task API, read responses safely, and handle loading, empty, and failure states.',goals:['Describe an API contract','Distinguish parsing from validation','Handle HTTP errors and unexpected data'],sections:[
{id:'contract',title:'1. Define the conversation',paragraphs:[`An application programming interface defines how software interacts with another component. In a web application, an HTTP API often lets a browser request data or ask a server to perform an operation. A caller works with a documented contract instead of knowing every implementation detail.`,`Consider a student task board. The browser needs tasks with an identifier, title, and completion flag. That shape is only the beginning. The contract should state which requests are allowed, how permission is checked, what happens when no tasks exist, and how errors are represented.`,`Write example requests and responses before implementing both sides. An example may reveal that the frontend expects an array while the backend returns an object containing an array. Finding the mismatch on paper is cheaper than debugging two running applications. The API in this guide is hypothetical; DevShelf does not provide these endpoints.`]},
{id:'json',title:'2. Read JSON as structured data',paragraphs:[`JSON represents objects, arrays, strings, numbers, booleans, and null. An object groups named values; an array represents an ordered collection. Here tasks is an array because several tasks may exist, and each task is an object whose fields describe a record. Property names and string values use double quotes.`,`A parser checks JSON syntax. It does not prove that the result matches application expectations. The text 42 is valid JSON but is not the task-list response below. An object with a tasks property might still contain wrong field types. Keep syntax checking separate from application validation.`,`Use the DevShelf formatter to expand and minify the example. Whitespace changes while the intended data model stays the same. Remove a required quote and observe the error. Then change done from false to the string "false". This remains valid JSON but changes the field's meaning and type.`],language:'JSON',code:`{
  "tasks": [
    { "id": "task-1", "title": "Review networking notes", "done": false },
    { "id": "task-2", "title": "Practice Python functions", "done": true }
  ]
}`},
{id:'http',title:'3. Distinguish response outcomes',paragraphs:[`An HTTP response contains a status and may include headers and a body. A successful request can return an empty collection. A failed request might return structured error data or an HTML page generated by infrastructure. Do not assume every response has the JSON shape expected for success.`,`An empty tasks array is normal for our task board. The interface can explain that no tasks have been added. A permission failure needs a different response, such as asking the user to sign in when appropriate. A server failure should never be presented as an empty list, because that falsely suggests existing tasks disappeared.`,`Sketch loading, populated, empty, and error states separately. Decide whether previous results stay visible during refresh, where retry controls belong, and whether the action is safe to repeat. The user needs to distinguish having no information from waiting for information or failing to retrieve it.`]},
{id:'fetch',title:'4. Request and validate data',paragraphs:[`Browser fetch returns a response for HTTP error statuses such as 404, so check response.ok rather than relying only on promise rejection. Reading with response.json is asynchronous and can fail if the content is not JSON. The function below handles these stages explicitly.`,`After parsing, validate the fields your application needs. Here tasks must be an array, and every item must contain expected primitive fields. A larger application may use a schema library for nested data or shared contracts. The principle is the same: received data is not automatically valid application data.`,`Run this example only in a project with a matching /api/tasks endpoint. It is an integration example, not a live public service. A caller should catch failures and show a useful error rather than leaving an unhandled promise rejection in the console.`],language:'JavaScript',code:`async function loadTasks() {
  const response = await fetch('/api/tasks', {
    headers: { Accept: 'application/json' }
  });
  if (!response.ok) {
    throw new Error('Task request failed: ' + response.status);
  }
  const data = await response.json();
  if (!data || !Array.isArray(data.tasks)) {
    throw new Error('Expected a tasks array');
  }
  const valid = data.tasks.every(task =>
    task !== null && typeof task === 'object' &&
    typeof task.id === 'string' &&
    typeof task.title === 'string' &&
    typeof task.done === 'boolean'
  );
  if (!valid) throw new Error('Unexpected task data');
  return data.tasks;
}`},
{id:'writes',title:'5. Design changes and permissions together',paragraphs:[`Reading and changing tasks have different consequences. Define what a write operation accepts and who may perform it. Hiding a button is not access control: a caller can construct a request outside the interface. The server owning the data must enforce permission for the operation.`,`A completion request also raises timing questions. What if the user clicks twice? What if the request succeeds but its response is lost? What if another device changes the task? Explicitly setting done to true can be easier to reason about than blindly toggling it with every repeated request. The API's documented semantics determine the right approach.`,`Keep private service credentials on the server when required by the design. A value sent to browser JavaScript is available to the browser's user. Renaming it or using Base64 does not make it secret. Base64 is a representation format, not encryption. This distinction matters when a local exercise becomes a shared application.`]},
{id:'diagnose',title:'6. Diagnose failure systematically',paragraphs:[`Inspect the request URL, method, status, and response body in the Network panel. Compare them with the contract. Did the frontend call the wrong path? Did the server return an error object or HTML? Gather observations before changing code. Separate routing problems from parsing and permission problems.`,`Browser cross-origin rules can prevent a page from reading another origin's response unless the server permits the interaction. Switching fetch to no-cors is not a general fix for reading blocked JSON; an opaque response is not normally readable. Use supported server configuration or an appropriate backend integration.`,`Test an empty array, a missing field, a wrong type, an HTTP error, and invalid JSON. Consider overlapping searches: an older response should not unexpectedly replace a newer result. Cancellation or request tracking may be appropriate depending on the interface.`,`Reliable API integration rests on explicit agreements. The caller requests a defined operation, the server verifies and performs it, and the interface communicates the outcome honestly. When these agreements are visible, testing and debugging become systematic instead of a sequence of guesses.`]}],exercise:['Introduce a syntax error in the example JSON and inspect the formatter result.','Change a completion flag into a string and explain why parsing does not reject it.','Write different interface messages for loading, empty data, and failure.'],answer:'Missing quotes should cause a parsing error. A string-valued flag remains valid JSON but violates the expected schema. Use distinct messages such as “Loading tasks,” “No tasks yet,” and “Could not load tasks—try again” so a failed request is never mistaken for an empty account.',glossary:[['API contract','The agreement about requests, responses, and behavior.'],['JSON','A text format for structured data.'],['Validation','Checking whether data satisfies application rules.'],['HTTP status','A code describing an HTTP request outcome.']],sources:[{title:'MDN: HTTP overview',url:'https://developer.mozilla.org/en-US/docs/Web/HTTP/Guides/Overview'},{title:'MDN: Using Fetch',url:'https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch'}]});
guides.push({slug:'networking-troubleshooting',title:'Networking fundamentals: trace a connection before fixing it',category:'IT foundations',summary:'Understand addresses, ports, DNS, and a practical troubleshooting process for local and remote services.',goals:['Distinguish a host from a service','Understand localhost and DNS','Use evidence to narrow connection failures'],sections:[
{id:'layers',title:'1. Separate the pieces of a connection',paragraphs:[`A student reports that a learning portal is unavailable. That description could mean the laptop has no network connection, the hostname cannot be resolved, the server is unreachable, or the application returns an error. These failures live at different parts of the path. Changing application code will not fix every connection problem.`,`Begin with a map: device, local network, router, destination host, and application service. The diagram need not represent every cable or provider. It should identify the boundaries where you can observe a different result. Write down the exact address and error message before trying a fix.`]},
{id:'address',title:'2. An address identifies a destination, a port identifies a service',paragraphs:[`An IP address helps traffic reach a network interface. A transport port distinguishes a service endpoint on that host. One computer can run several services without assigning each one a separate physical network card. A website might listen on one port while a development API uses another.`,`For http://localhost:3000, localhost refers to the device making the request and 3000 identifies the requested port. Opening that address on a phone refers to the phone, not your laptop. A URL that works on the development computer is therefore not automatically a shareable website address.`]},
{id:'names',title:'3. Names add a separate lookup step',paragraphs:[`DNS translates names into records that help clients find services. A human-readable hostname can stay stable while the infrastructure behind it changes. Name resolution and application availability are separate questions: a valid DNS response does not prove a web application is healthy.`,`A browser may reuse cached information, and a service may have several addresses. Record which hostname you tested and when. If one application works while another fails, avoid immediately concluding that the entire internet connection is broken. Compare the specific destinations and symptoms.`]},
{id:'local',title:'4. Start with a service you control',paragraphs:[`For a local web project, first verify that the development server is running and note the exact address it prints. If it moved to another port because the original was occupied, the old browser tab may point at the wrong process. Read the server output instead of assuming the port.`,`An HTTP response, including an error status, tells you that some server answered. A connection refusal often points toward no listener at the selected endpoint or an active rejection. A timeout is less specific and requires more evidence. Treat symptoms as clues rather than definitive diagnoses.`],language:'PowerShell · local read-only check',code:`# Run while your own development server is listening.
Invoke-WebRequest http://localhost:3000/ -SkipHttpErrorCheck
# Inspect StatusCode and the server log together.`},
{id:'method',title:'5. Change one variable at a time',paragraphs:[`Build a short investigation table with test, observation, and implication. “Homepage returns 200 but /api/tasks returns 404” is a much stronger clue than “network broken.” It suggests investigating the route or endpoint configuration before replacing network settings.`,`Test only systems you own or are authorized to troubleshoot. Preserve the failing condition long enough to gather useful evidence. Repeatedly restarting everything may hide the symptom without explaining it, making the next occurrence just as difficult to investigate.`]},
{id:'handoff',title:'6. Write a useful support handoff',paragraphs:[`A useful report includes the affected feature, exact URL with sensitive values removed, time of failure, expected behavior, actual result, and tests already performed. Mention whether the failure affects one device or several. Include relevant status codes without copying private response data unnecessarily.`,`After a fix, repeat the original failing steps and test a nearby successful case. Document what changed and why it addresses the observation. The goal is a repeatable explanation, not a lucky recovery that nobody can reproduce.`]}],exercise:['Explain why localhost on two devices can show different results.','Compare a missing route with a stopped local server.','Write a three-line incident report for a failing task endpoint.'],answer:'Each device resolves localhost to itself. A missing route can return an HTTP 404 from a running server, while a stopped listener cannot serve that request. A useful report names the route, observed status or connection error, and the successful comparison test.',glossary:[['Port','A numbered transport endpoint used to distinguish services.'],['Localhost','A hostname referring to the device making the request.'],['DNS','A distributed naming system that returns records for names.']],sources:[{title:'MDN: Client-server overview',url:'https://developer.mozilla.org/en-US/docs/Learn_web_development/Extensions/Server-side/First_steps/Client-Server_overview'},{title:'MDN: HTTP overview',url:'https://developer.mozilla.org/en-US/docs/Web/HTTP/Guides/Overview'}]});
guides.push({slug:'linux-command-line',title:'Linux essentials: files, processes, and a careful terminal workflow',category:'IT foundations',summary:'Navigate a Linux environment, inspect files and running processes, and understand permissions without guessing.',goals:['Read paths confidently','Inspect before changing files','Recognize process and permission problems'],sections:[
{id:'shell',title:'1. Know what the terminal is running',paragraphs:[`A terminal provides an interface to a shell. The shell interprets commands and launches programs. A command may be built into the shell or supplied by a separate executable. The examples in this lesson assume a Linux environment with a Bash-like shell; they are not PowerShell commands.`,`Working in a terminal does not make an action inherently more correct than using a graphical interface. Its advantage is precision and repeatability. That precision also means a wrong path can target the wrong file. Begin every unfamiliar session by establishing where you are.`]},
{id:'paths',title:'2. Orient yourself before editing',paragraphs:[`An absolute path begins at the filesystem root. A relative path is interpreted from your current working directory. The same relative filename can refer to different files after you change directories. This is why a command copied from instructions may behave differently in your current shell.`,`Use the read-only commands below to establish context. Then move into a practice directory you created for learning. Quote filenames containing spaces. Prefer a small directory containing disposable exercises when learning unfamiliar file operations.`],language:'Linux shell',code:`pwd
ls -la
# Read a small text file that exists in the current directory.
cat "notes.txt"
# Inspect running processes.
ps -ef`},
{id:'streams',title:'3. Think of commands as producers and consumers',paragraphs:[`Many command-line tools receive input and produce output. A pipe can connect the output of one command to the input of another. This makes small tools useful in combination. Before composing a long pipeline, run each step separately and inspect the result.`,`Output redirection is different from simply displaying text. Redirecting to a file can replace its contents depending on the operator used. Read the command carefully before running it, especially when an example includes a path that already contains important work. A terminal usually cannot infer what you meant to preserve.`]},
{id:'permissions',title:'4. Treat permission errors as information',paragraphs:[`Linux permissions associate access rights with an owner, group, and other users. A permission failure can mean your current account is not allowed to read, write, or execute the requested item. It can also reveal that the file was created under a different account than expected.`,`Do not respond to every failure by adding elevated privileges. First inspect the path, ownership, and the operation's purpose. Ask whether this account should perform the action at all. Broadly making project files writable may hide one error while introducing a larger maintenance or security problem.`]},
{id:'processes',title:'5. Distinguish files from running programs',paragraphs:[`A process is a running instance of a program. Saving a file does not always cause a running service to reload it. Conversely, deleting or changing a source file may not immediately stop an already-running process. You need to understand how the application loads configuration and code.`,`When a service fails, gather its logs and confirm whether it is still running. Note the user account and launch method. A program started manually in your terminal may not behave like the same program launched as a managed service because its environment and working directory can differ.`]},
{id:'routine',title:'6. Build a repeatable routine',paragraphs:[`Use a short routine: establish the directory, inspect the target, perform one intended action, and verify the result. Keep notes about commands that solve a specific problem, including the assumptions under which they work. A copied command without context is a poor troubleshooting record.`,`For each exercise, explain the before and after state. If you cannot describe which files or processes are affected, pause and read the relevant manual. Competence at the terminal grows from understanding scope and consequences rather than typing long commands quickly.`]}],exercise:['Find your current directory and list its hidden entries.','Explain how a relative path changes meaning after changing directories.','Describe why a permission error does not automatically justify elevated privileges.'],answer:'pwd shows the current directory and ls -la includes hidden entries. Relative paths start from that directory. Before escalating privileges, inspect ownership and confirm that the requested operation belongs to your account and task.',glossary:[['Shell','A command interpreter that launches programs.'],['Process','A running instance of a program.'],['Relative path','A path interpreted from the current directory.']],sources:[{title:'Ubuntu: The Linux command line for beginners',url:'https://ubuntu.com/tutorials/command-line-for-beginners'}]});
guides.push({slug:'sql-data-models',title:'Databases and SQL: model the information before querying it',category:'Data & backend',summary:'Build a small course catalog, write readable queries, and reason about keys, constraints, and transactions.',goals:['Design records with stable identifiers','Read and filter data using SQL','Understand constraints and atomic changes'],sections:[
{id:'model',title:'1. Start with the questions your data must answer',paragraphs:[`A learning platform needs to know which courses exist, who enrolled, and which lessons a learner completed. Putting everything into one text field makes those questions difficult to answer reliably. A data model gives each important concept a defined structure and explains how records relate.`,`Write the questions first: which courses are published, which enrollments belong to one learner, and which lessons remain incomplete? These questions guide the fields and relationships you need. Avoid collecting extra personal information just because a database makes it easy to add another column.`]},
{id:'keys',title:'2. Separate identity from display text',paragraphs:[`A primary key identifies a row. A course title is usually a poor identity because titles can change and two courses can have similar names. A stable course identifier lets other tables refer to the course without duplicating its entire description.`,`An enrollment can connect a learner identifier with a course identifier. A foreign key can require referenced records to exist. Constraints represent rules the database should enforce even when several application paths write to it. Interface validation alone cannot guarantee consistent stored data.`]},
{id:'query',title:'3. Read a result deliberately',paragraphs:[`The example uses a temporary PostgreSQL table in your own practice database. Its name reduces the chance of colliding with a real table. The SELECT statement chooses columns, filters rows, and applies an explicit ordering. Without ORDER BY, do not rely on a particular row order.`,`Run the query, predict the returned titles, then change the filter. Explain which rows were excluded and why. Selecting only the fields needed by a caller can make the result easier to understand than indiscriminately returning every column.`],language:'PostgreSQL · practice session',code:`CREATE TEMP TABLE learning_catalog_demo (
  id integer PRIMARY KEY,
  title text NOT NULL,
  published boolean NOT NULL DEFAULT false
);
INSERT INTO learning_catalog_demo (id, title, published)
VALUES (1, 'Web basics', true), (2, 'SQL practice', false);

SELECT id, title
FROM learning_catalog_demo
WHERE published = true
ORDER BY title;`},
{id:'changes',title:'4. Make related changes together',paragraphs:[`Suppose enrollment consumes the last available seat. Updating the enrollment and seat count as unrelated operations can leave inconsistent data if one step fails. A transaction groups work so the application can commit the intended changes together or roll them back.`,`Concurrency adds another question: what happens when two people request the final seat simultaneously? A successful interface check performed seconds earlier is insufficient. The database operation must enforce the rule at the moment of the change, using an appropriate transaction and concurrency design.`]},
{id:'inputs',title:'5. Keep values separate from query structure',paragraphs:[`When application input becomes part of a query, use the database driver's parameter mechanism. Building SQL by concatenating user text can allow that text to alter query meaning. The exact placeholder syntax depends on the driver; follow its documentation rather than copying a placeholder from another language.`,`Validate inputs according to product rules as well. A parameterized query protects query structure, but it does not decide whether a requested course is available or whether the caller can edit it. These are separate checks with separate purposes.`]},
{id:'operations',title:'6. Plan for changes and recovery',paragraphs:[`A migration records a deliberate schema change. Review how existing data will fit a new constraint before applying it. Adding a required field raises questions about old rows, default values, and the order in which application and database changes are released.`,`An index can help a database locate relevant rows, but it also uses storage and affects writes. Measure an actual query and inspect its plan before adding indexes indiscriminately. Finally, test restoration from backups. A backup that exists but cannot be restored has not demonstrated the recovery your application needs.`]}],exercise:['Predict the sample query result.','Explain why a course title should not be the only identifier.','Describe what must happen if a two-step enrollment transaction fails halfway.'],answer:'The query returns Web basics, because SQL practice is unpublished. A stable identifier survives title changes. If the intended changes are in one transaction and the operation fails, roll it back so a partial enrollment does not remain.',glossary:[['Primary key','A column or set of columns uniquely identifying a row.'],['Constraint','A database-enforced rule on stored data.'],['Transaction','A unit of work that can be committed or rolled back.']],sources:[{title:'PostgreSQL: SQL tutorial',url:'https://www.postgresql.org/docs/current/tutorial-sql.html'}]});
guides.push({slug:'security-by-design',title:'Security basics: protect a feature from the first design',category:'Security',summary:'Reason about identity, permissions, untrusted input, secrets, and recovery using a student portal.',goals:['Separate authentication from authorization','Locate trust boundaries','Plan concrete security checks for one feature'],sections:[
{id:'assets',title:'1. Decide what you are protecting',paragraphs:[`Security begins with understanding the feature and the people affected. A student portal might store profile details, coursework, and teacher feedback. A public course title has different handling requirements from a private submission. List the information involved and who should be able to read or change it.`,`Consider mistakes as well as deliberate abuse. An incorrectly configured link can expose a document without anyone exploiting complicated code. A design review should ask what happens when the wrong person receives a URL, an account is compromised, or a support operator chooses the wrong record.`]},
{id:'identity',title:'2. Verify identity and permission separately',paragraphs:[`Authentication establishes an identity. Authorization decides whether that identity may perform a particular action on a particular resource. Being signed in does not mean a learner may read another learner's submissions. A role label in the interface does not enforce the rule.`,`For a submission endpoint, the server should connect the caller to the requested record and check the relevant policy. Test two ordinary accounts with separate records. A request that succeeds for its owner should fail for an unrelated learner unless sharing was intentionally granted.`]},
{id:'boundaries',title:'3. Treat received values as untrusted',paragraphs:[`Browser forms are only one way to send data. A caller can bypass them or modify a request. Validate expected structure, types, ranges, and allowed operations at the boundary that owns the decision. Render user text using safe text handling instead of interpreting it as executable markup.`,`A filename supplied by a user should not automatically become a filesystem path. An identifier should not automatically grant access to the matching row. Look for places where received data is transformed into an instruction, location, or privileged operation. These boundaries deserve explicit design.`]},
{id:'secrets',title:'4. Give secrets a controlled lifecycle',paragraphs:[`A private API credential included in frontend JavaScript is available to the user running that JavaScript. Encoding it or using an obscure variable name does not make it private. Keep credentials in an appropriate server-side secret mechanism and restrict their scope to the work they need to perform.`,`Plan what happens if a credential is exposed: revoke or rotate it, identify where it was used, and check affected systems. Removing a key from the latest source file is not enough if it remains valid or appears in old history. Prevention and recovery should both have an owner.`]},
{id:'verification',title:'5. Turn rules into checks',paragraphs:[`Write a small permission matrix for the submission feature. An owner may read their submission, a designated reviewer may evaluate it, and an unrelated learner may do neither. Test those outcomes through the actual server interface, not merely by inspecting which buttons are visible.`,`Use meaningful negative cases. Try an unknown record, a record owned by someone else, and a malformed request. Confirm that errors do not reveal unnecessary private details. Keep test accounts and data separate from real sensitive material.`],language:'Example permission matrix',code:`Action: read a private submission
Owner                 → allowed
Assigned reviewer     → allowed by review policy
Unrelated learner     → denied
Unauthenticated caller → denied`},
{id:'maintenance',title:'6. Keep protection working over time',paragraphs:[`Security changes as a product gains features and dependencies. Review new data flows, apply supported updates, and monitor events that help identify failures. Logs should support investigation without becoming a second uncontrolled store of passwords, credentials, or private content.`,`Use a risk reference such as OWASP to guide questions, not as proof that a feature is secure because a checklist was ticked. A useful final review ties each important rule to evidence: where it is enforced, how it was tested, and how the team would detect and recover from a failure.`]}],exercise:['Write a permission matrix for a private assignment.','Explain why hiding an edit button is insufficient.','List the actions needed after a private API key is exposed.'],answer:'The server must enforce the matrix for each requested record. Hidden buttons do not stop direct requests. An exposed key needs revocation or rotation, investigation of its usage and scope, and removal from places where it was unintentionally distributed.',glossary:[['Authentication','Establishing the identity of a caller.'],['Authorization','Deciding whether a caller may perform an operation.'],['Trust boundary','A point where data crosses between different levels of trust.']],sources:[{title:'OWASP: Web application security risk reference',url:'https://owasp.org/www-project-top-ten/'}]});
guides.push({slug:'containers-and-delivery',title:'Containers and cloud delivery: understand what runs where',category:'Cloud & operations',summary:'Separate an image from a running container, plan persistent data, and design a basic release workflow.',goals:['Explain images and containers','Separate configuration from an artifact','Plan health checks and recovery'],sections:[
{id:'environment',title:'1. Make the runtime explicit',paragraphs:[`An application that works on one laptop can fail elsewhere because a runtime, library, environment variable, or system dependency differs. The first step toward repeatability is identifying these assumptions. Write down how the program starts, what it depends on, and which resources it expects to reach.`,`A container image packages a filesystem and runtime configuration used to launch a container. A container is a running instance based on that image. This can reduce differences between environments, but it does not make an application independent of architecture, host capabilities, network configuration, or external services.`]},
{id:'artifact',title:'2. Separate the release artifact from its settings',paragraphs:[`Treat a release artifact as something you can identify precisely. If development and production each rebuild different dependencies, the two environments may not be running the same program. A repeatable pipeline should make it clear which source and dependencies produced the deployed artifact.`,`Configuration often differs by environment. A development database address should not be baked into an artifact intended for production. Supply configuration through supported runtime mechanisms, keep private values out of client bundles, and validate required settings at startup so a missing value creates an understandable failure.`]},
{id:'data',title:'3. Decide which data must survive',paragraphs:[`A running container may have writable state, but replacing the container can remove data stored only there. Application logs, uploads, and database records have different storage requirements. Classify each one before selecting a persistence mechanism.`,`A volume or external data service can preserve information beyond one container lifecycle, but persistence is not the same as backup. Ask how accidental changes are recovered, who controls access, and how restoration is tested. A containerized application still needs a data-management plan.`]},
{id:'network',title:'4. Trace the service boundary',paragraphs:[`A program can listen inside a container without being reachable at the host address a browser uses. Published ports and network configuration determine how traffic reaches the service. Trace the request from the user's URL through each boundary rather than assuming that starting a process makes it publicly accessible.`,`Containers provide isolation mechanisms, not a guarantee that arbitrary code is harmless. Run only the privileges and capabilities the application needs. If an exercise requires a container engine, follow the vendor's setup guidance in your own development environment before attempting to launch workloads.`]},
{id:'release',title:'5. Build a release checklist around behavior',paragraphs:[`A basic pipeline can install defined dependencies, run relevant checks, build an artifact, and release that artifact to a chosen environment. Each step should fail clearly when its prerequisite is missing. A successful build proves something narrower than a successful user journey.`,`After a release, verify a meaningful operation such as loading the catalog or submitting a test form. Health checks should reflect the purpose of the service rather than merely the existence of a process. Record the release identifier so an observed failure can be connected to the code that is running.`],language:'Conceptual release flow',code:`Source revision
  → dependency installation
  → relevant tests
  → build artifact
  → release to selected environment
  → verify health and a user journey`},
{id:'recovery',title:'6. Plan a way back before you need it',paragraphs:[`A rollback should have a clearly identified target, such as the previous known-good artifact. Database changes can complicate reversal: older code may not understand a new schema. Favor compatible transitions when appropriate and document the sequence needed for recovery.`,`Collect logs and measurements that answer operational questions: did the service start, are requests failing, and is latency changing? Avoid collecting data without a plan to use it. A useful operations routine makes the deployed system understandable to the next person responsible for it.`]}],exercise:['Explain image versus container in one sentence each.','List which data a learning portal must preserve across a release.','Define a post-release check more useful than “the process is running.”'],answer:'An image is a launchable artifact; a container is an instance running from it. Enrollment and completion records need durable storage and a recovery plan. Loading a known course and verifying a test enrollment checks meaningful behavior after release.',glossary:[['Image','A packaged artifact used to create containers.'],['Container','An isolated process environment launched from an image.'],['Artifact','An identified output of the build process.']],sources:[{title:'Docker: What is a container?',url:'https://docs.docker.com/get-started/docker-concepts/the-basics/what-is-a-container/'}]});
guides.push({slug:'testing-and-debugging',title:'Testing and debugging: turn uncertainty into evidence',category:'Developer workflow',summary:'Choose useful test cases, write a small automated check, and investigate a failure systematically.',goals:['Choose tests from behavior','Recognize useful boundary cases','Build a reproducible debugging report'],sections:[
{id:'purpose',title:'1. Describe the behavior you need confidence in',paragraphs:[`Testing is most useful when it answers a concrete question. Does a calculation reject an impossible input? Can one learner access another learner's work? Does the interface preserve a draft when a request fails? The answer determines which level of test provides useful evidence.`,`A unit test focuses on a small piece of logic. An integration test checks cooperating parts, such as an application and its storage interface. A user-journey test follows a visible workflow. These categories can overlap; their names matter less than knowing what a passing test actually demonstrates.`]},
{id:'cases',title:'2. Derive cases from the requirement',paragraphs:[`Suppose a lesson progress display accepts completed and total counts. A simple rule might return a rounded percentage, reject negative values, and reject completed counts greater than total. Decide how zero total is represented before writing the function. Otherwise two implementations can disagree while both seem reasonable.`,`List ordinary, boundary, and invalid examples. For each one, write an expected result or expected failure. Do not generate expected values using the exact same formula under test, because the test could repeat the implementation's mistake instead of detecting it.`]},
{id:'example',title:'3. Write a small, executable test',paragraphs:[`Save this example as progress.test.mjs and run it with node --test progress.test.mjs in a Node.js environment supporting the built-in test runner. It defines a deliberately limited rule for valid integer counts. A production implementation should document the allowed domain just as clearly.`,`The invalid-case assertion checks that an impossible count is rejected. The other assertion checks an expected result. Add a zero-total test and an exact-completion test yourself. Test names should explain the behavior to someone reading a failure report.`],language:'JavaScript · Node.js',code:`import test from 'node:test';
import assert from 'node:assert/strict';

function progress(done, total) {
  if (!Number.isInteger(done) || !Number.isInteger(total) ||
      done < 0 || total < 0 || done > total) {
    throw new RangeError('Invalid lesson counts');
  }
  return total === 0 ? 0 : Math.round(done / total * 100);
}

test('one of four lessons is 25 percent', () => {
  assert.equal(progress(1, 4), 25);
});
test('completed count cannot exceed total', () => {
  assert.throws(() => progress(5, 4), RangeError);
});`},
{id:'investigate',title:'4. Debug from a repeatable observation',paragraphs:[`When a defect appears, record the smallest sequence that reproduces it. Include the relevant input and environment. “Progress shows 125% after completing an imported course” is more actionable than “the dashboard is wrong.” The first statement points toward a violated count relationship.`,`Form one hypothesis and gather evidence. Inspect the values entering the calculation and compare them with the data source. If the inputs are already inconsistent, changing a rounding rule will not address the real cause. Work backward until you locate the boundary where the requirement stopped being enforced.`]},
{id:'doubles',title:'5. Understand what isolation leaves out',paragraphs:[`Replacing a network call with a test double can make a test fast and predictable. It also means that test does not prove the real network integration works. Use isolation deliberately and add an appropriate integration check when the interaction itself matters.`,`A large number of passing assertions is not a guarantee of useful coverage. Tests that merely confirm implementation details can make refactoring painful without protecting user behavior. Prefer observable results and explicit rules, then add narrower implementation checks only where they address a real risk.`]},
{id:'fix',title:'6. Verify the fix and nearby behavior',paragraphs:[`After fixing the cause, repeat the original reproduction steps. Add a regression test when it meaningfully protects the behavior. Check a nearby valid case to make sure the fix did not solve the failure by rejecting legitimate input.`,`A useful completion note states what failed, what changed, and what evidence now supports the result. It should also name any important limit, such as a test that used simulated network responses. Clear evidence lets a reviewer judge confidence without assuming that every possible environment was tested.`]}],exercise:['Add zero-total and exact-completion tests.','Write a failing case for a fractional completed count.','Explain which integration risks the small function tests do not cover.'],answer:'progress(0,0) returns 0 and progress(4,4) returns 100. A fractional count should throw. These tests do not verify database records, real HTTP responses, or browser rendering; those need checks at the relevant integration boundary.',glossary:[['Regression test','A check intended to catch a previously identified failure.'],['Test double','A controlled replacement for a dependency during a test.'],['Reproduction','A repeatable sequence that demonstrates an issue.']],sources:[{title:'Node.js: Test runner',url:'https://nodejs.org/api/test.html'}]});
guides.push({slug:'react-interface-state',title:'React foundations: build interfaces around data and state',category:'Web foundations',summary:'Break a course catalog into components and keep filtering behavior understandable.',goals:['Separate component responsibilities','Distinguish props from state','Avoid duplicated derived values'],sections:[
{id:'structure',title:'1. Begin with a static interface',paragraphs:[`Imagine a course catalog with a search field and several course cards. Before adding interactions, identify the visible parts and the data each part needs. A catalog contains a toolbar and a list; a card displays one course. This gives the interface a structure that can be understood without following every event handler.`,`Build the static presentation with representative data first. Check long titles, missing optional descriptions, and a narrow viewport. These cases reveal layout problems before interactive state complicates the investigation. A component should have a useful responsibility rather than exist solely because a file became long.`]},
{id:'inputs',title:'2. Use props to communicate inputs',paragraphs:[`Props supply information to a component from its parent. A course card can receive a title and summary without knowing how the catalog loaded them. That separation makes the card easier to reuse and inspect. Keep the direction of information clear so a reader can trace where a displayed value originates.`,`Use stable identifiers for list keys. The identity of a course should not change when the user filters the list or changes its order. A position in an array describes where something appears now, not necessarily which item it is.`]},
{id:'state',title:'3. Store only what changes independently',paragraphs:[`State represents information the component needs to remember between renders. The search query is state because user input changes it. The filtered list can be calculated from the query and course data; storing another copy in state creates a synchronization problem.`,`Ask whether a value can be computed from existing props or state. If it can, calculate it during rendering unless there is a measured reason to choose a different approach. Avoid adding an effect merely to keep two copies of the same information aligned.`]},
{id:'example',title:'4. Connect a controlled input',paragraphs:[`This example belongs inside a React application. It renders a labeled search field and derives the visible courses from its current query. The input's value and change handler make the relationship between user input and component state explicit.`,`Try searching for SQL, then clear the field. Add a query that matches nothing and observe the empty state. A real catalog should also distinguish data that is still loading from a successful result containing no courses.`],language:'React JSX',code:`import { useState } from 'react';
const courses = [
  { id: 'web', title: 'Web foundations' },
  { id: 'sql', title: 'SQL essentials' }
];
export default function Catalog() {
  const [query, setQuery] = useState('');
  const visible = courses.filter(course =>
    course.title.toLowerCase().includes(query.toLowerCase())
  );
  return <section>
    <label htmlFor="course-search">Find a course</label>
    <input id="course-search" value={query}
      onChange={event => setQuery(event.target.value)} />
    <ul>{visible.map(course =>
      <li key={course.id}>{course.title}</li>
    )}</ul>
    {visible.length === 0 && <p>No matching courses.</p>}
  </section>;
}`},
{id:'ownership',title:'5. Give shared state a clear owner',paragraphs:[`When two components need the same selected course, choose a common owner for that information and pass the relevant value and actions downward. Two independent selections can drift apart and produce contradictory interfaces. The simplest appropriate owner is often their nearest shared parent.`,`Do not move every temporary value into global state by default. A draft visible only in one small form can often stay local. Choose ownership based on which parts need coordination, not on a belief that one storage location suits every interaction.`]},
{id:'quality',title:'6. Verify the interface as a person uses it',paragraphs:[`Test keyboard focus, long labels, empty results, and narrow screens. Check that clearing a filter restores the expected content. If a request can fail, preserve the user's choices while showing an actionable message. Framework correctness does not automatically create a useful interaction.`,`As the application grows, keep components focused on meaningful tasks and data flows. Read a feature from input to state to rendered output. If the relationship is hard to explain, simplify ownership and remove redundant state before adding another abstraction.`]}],exercise:['Add a third course with a stable identifier.','Explain why visible is calculated rather than stored separately.','Design a category filter that combines with the text query.'],answer:'Add a record with a unique id. The visible list derives from courses and query, so storing it would duplicate information. A category filter can be another state value; calculate results using both the category condition and text match.',glossary:[['Props','Inputs passed from a parent to a component.'],['State','Information remembered between renders.'],['Derived value','A result calculated from information already available.']],sources:[{title:'React: Thinking in React',url:'https://react.dev/learn/thinking-in-react'},{title:'React: Quick start',url:'https://react.dev/learn'}]});
guides.push({slug:'typescript-data-contracts',title:'TypeScript essentials: describe data without trusting it blindly',category:'Programming',summary:'Model course records, narrow optional values, and understand where compile-time checking ends.',goals:['Describe an object with a type','Use unions to represent alternatives','Validate data received at runtime'],sections:[
{id:'role',title:'1. Know what TypeScript checks',paragraphs:[`TypeScript adds a type-checking layer to JavaScript development. It helps identify mismatches before the program runs, such as passing a number where a title string is expected. The emitted JavaScript does not automatically validate every value arriving from a network, file, or user.`,`This distinction is essential when integrating an API. A declared type is a claim made by your program. An external response must still be checked at the boundary. Using a type assertion to silence an error does not transform an invalid response into the promised data.`]},
{id:'shape',title:'2. Model one record clearly',paragraphs:[`A course record needs a stable id, a title, and a publication status. An optional summary means a caller must consider that the field might be absent. A union can describe a limited set of allowed alternatives more accurately than an unrestricted string.`,`Choose names that reflect the product rather than implementation convenience. If a field means estimated reading minutes, name it accordingly. A numeric type alone cannot tell a teammate whether a value represents seconds, minutes, or a progress percentage.`],language:'TypeScript',code:`type Course = {
  id: string;
  title: string;
  status: 'draft' | 'published';
  summary?: string;
};

function courseLabel(course: Course): string {
  return course.status === 'published'
    ? course.title
    : course.title + ' (draft)';
}`},
{id:'narrow',title:'3. Narrow values before using them',paragraphs:[`A value that might be missing needs a decision before being used as a definite string. A default summary can be appropriate for display, while a required enrollment identifier should probably cause validation to fail. Optionality is a product question as well as a syntax feature.`,`Branching on a value can narrow its possible types. For example, checking whether a value is a string lets subsequent code use string operations in that branch. Prefer this evidence-based narrowing to broad assertions that tell the checker to assume your conclusion.`]},
{id:'boundary',title:'4. Keep unknown data unknown until checked',paragraphs:[`The unknown type requires you to inspect a value before using it as a particular shape. This is useful at external boundaries. The guard below checks a small subset of the course contract and can be extended when additional fields become necessary.`,`A validator should match what downstream code relies on. If a later operation expects a nonempty identifier, checking only typeof value.id is insufficient. Separate basic type shape from additional domain rules and test both deliberately.`],language:'TypeScript',code:`function isCourse(value: unknown): value is Course {
  if (typeof value !== 'object' || value === null) return false;
  const item = value as Record<string, unknown>;
  return typeof item.id === 'string' &&
    typeof item.title === 'string' &&
    (item.status === 'draft' || item.status === 'published') &&
    (item.summary === undefined || typeof item.summary === 'string');
}`},
{id:'errors',title:'5. Read type errors as design feedback',paragraphs:[`A type error sometimes reveals a real disagreement between components. One function may return an optional result while its caller assumes success. Instead of immediately adding an assertion, decide what should happen when the result is absent. A useful type model makes that choice visible.`,`Avoid using any as a universal escape hatch. It can remove the very checks you added TypeScript to obtain. When a library's type is difficult, inspect the relevant API and narrow the uncertainty to a small boundary rather than weakening the whole application.`]},
{id:'routine',title:'6. Pair type checking with runtime tests',paragraphs:[`A program can pass type checking and still calculate the wrong total, enforce the wrong permission, or render an inaccessible interface. Use types to improve consistency, then verify behavior with appropriate tests and real examples. Different checks answer different questions.`,`As a learning routine, model a record, write a function that consumes it, and intentionally supply a mismatched value. Observe the checker. Then pass malformed external data through a validator and observe the runtime outcome. Understanding both paths prevents overconfidence in either one.`]}],exercise:['Add an estimatedMinutes field and explain its unit.','Decide whether an empty title satisfies your product rules.','Explain why an API response asserted as Course can still be invalid.'],answer:'Use a numeric estimatedMinutes field and validate the allowed range at runtime. A string check permits an empty title, so add a separate nonempty rule if required. A type assertion does not inspect or modify received data; only actual runtime validation can establish its shape.',glossary:[['Union','A type representing one of several alternatives.'],['Narrowing','Reducing possible types based on checks or control flow.'],['Type assertion','A developer instruction to the checker, not runtime validation.']],sources:[{title:'TypeScript: Everyday types',url:'https://www.typescriptlang.org/docs/handbook/2/everyday-types.html'}]});

